rss/urls.py
from django.urls import path, include
from . import views

urlpatterns= [
    path('', views.index, name='index'),
    path('update_product/<pk>', views.UpdateProduct, name='update-product'),
    path('delete_product/<pk>', views.DeleteProduct, name='delete-product'),
]

test_feeds/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rss.urls')),
]

rss/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Product(models.Model):
    title = models.CharField(max_length=255,blank=True,null=True)
    description = models.CharField(max_length=3000,blank=True,null=True)
    website = models.URLField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True )
    publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

rss/forms.py
from django import forms
from .models import *
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control','type' :'text'}),
            'description': forms.Textarea(attrs={'class': 'form-control','type' :'text'}),
            'website': forms.TextInput(attrs={'class': 'form-control','type' :'text'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'publish': forms.DateInput(attrs={'class': 'form-control','type': 'date'}),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
        	'name' : forms.Select(attrs={'class': 'form-control'})
        }

rss/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import feedparser
from .forms import *

from .models import Category, Product
from django.views.generic import TemplateView, ListView
import datetime
import dateutil.parser

# Create your views here.

def index(request):

    if request.GET.get("url"):
        url_text = request.GET["url"] #Getting URL
        url_text = url_text.replace(',',' ')
        url_text = url_text.split()
        for url in url_text:
            u = url.split('/')
            if not Category.objects.filter(name=u[-1]).exists():
                categoried = Category(name=u[-1])
                categoried.save()
            category = Category.objects.get(name=u[-1])
            
            feed = feedparser.parse(url) #Parsing XML data
            for entries in feed.entries:
                published_time = dateutil.parser.parse(entries.published)
                product = Product(title=entries.title,description=entries.summary,website=entries.link,category=category,publish=published_time)
                product.save()
    else:
        all_products = None

    
    PAGESIZE = 5
    category_id = request.GET.get("category", "")
    category_id = int(category_id) if category_id else ''
    all_products = Product.objects.all()
    
    if category_id:
        all_products = all_products.filter(category_id=category_id)
    
    all_products = all_products.order_by('id')
    paginator = Paginator(all_products, PAGESIZE)

    page = int(request.GET.get('page', 1))
    page = max(min(page, paginator.num_pages), 1)    
    all_products = paginator.page(page)
       
    return render(request, 'rss/reader.html', 
        { 
            'page':page, 
            'offset': (page-1)* PAGESIZE,
            'all_products' : all_products, 
            'categoried' : Category.objects.all(),
            'selected_category': category_id
        })

def UpdateProduct(request, pk):
    page = request.GET.get("page", "")
    categori_id = request.GET.get("selected_category", "")
    product = Product.objects.get(pk=pk)
    form = ProductForm(instance=product)

    if request.method == 'POST':
        form = ProductForm(request.POST,instance=product)
        page_id = request.POST['page']
        page_id = int(page_id) if page_id else ''
        category_id = request.POST['selected_category']
        category_id = int(category_id) if category_id else ''
        if form.is_valid():
            form.save()
            return redirect('/?page='+str(page_id)+'&category='+str(category_id))

    
    return render(request, 'rss/product_form.html', {
                    'form' : form,
                    'form_name': form.__class__.__name__,
                    'product_id': product.id,
                    'page': page,
                    'categori_id': categori_id,
                    })

def DeleteProduct(request, pk):
    product = Product.objects.get(pk=pk)
    product.delete()
    return redirect('/')

rss/templates/rss/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django RSS Reader</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ STATIC_URL }}sortable_listview/bootstrap.min.css">

</head>
<body>
    {% include 'rss/header.html' %}
    {% block body %}{% endblock %}
    {% include 'rss/footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

rss/templates/rss/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://github.com/baothi/test_feeds"> Test Feeds</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

rss/templates/rss/header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
        	<a class="nav-link" href="/">Home</a>
        </li>
    </ul>
</nav>

rss/templates/rss/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1&category={{selected_category}}">&laquo; first</a>
            <a href="?page={{ page.previous_page_number }}&category={{selected_category}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}&category={{selected_category}}">next</a>
            <a href="?page={{ page.paginator.num_pages }}&category={{selected_category}}">last &raquo;</a>
        {% endif %}
    </span>
</div>

rss/templates/rss/product_form.html
{% extends 'rss/base.html' %}
{% block body %}

<div class="container">
    <h1>Edit Product</h1>
    <hr>
    <form method="POST" action="{% url 'update-product' product_id %}" id="{{ form_name }}">
        {% csrf_token %}
        <input type="hidden" name="page" id="page_id" value="{{page}}">
        <input type="hidden" name="selected_category" id="selected_category" value="{{categori_id}}">
        <div class="form-group">
            <label class="col-lg-3 control-label">Title:</label>
            <div class="col-lg-8">
                {{form.title}}
                <div>{{ form.title.errors }}</div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-3 control-label">Description:</label>
            <div class="col-lg-8">
                {{form.description}}
                <div>{{ form.description.errors }}</div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-3 control-label">Website:</label>
            <div class="col-lg-8">
                {{form.website}}
                <div>{{ form.website.errors }}</div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-3 control-label">Category:</label>
            <div class="col-lg-8">
                <div class="ui-select">
                    {{form.category}}
                    <div>{{ form.category.errors }}</div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label">Publish:</label>
            <div class="col-md-8">
                {{form.publish}}
                <div>{{ form.publish.errors }}</div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
                <input type="submit" class="btn btn-primary" value="Save Changes">
                <span></span>
                <a class="btn btn-default" href='/'>Cancel</a>
            </div>
        </div>
    </form>
</div>
<hr>

{% endblock %}

rss/templates/rss/reader.html
{% extends 'rss/base.html' %}
{% block body %}
    <br/>
    <div class="container pt-3">
        <div class="row">
            <div class="col-md-6 col-md-offset-1">
                <form action="{% url 'index' %}" >
                    <div class="form-group mx-sm-3 mb-2">
                        <input type="text" class="form-control" placeholder="paste link" name="url">
                    </div>
                    <button type="submit" class="btn btn-outline-primary mb-2">Feed Rss</button>

                </form>
            </div>
            <div class="col-md-6 col-md-offset-2">
                {% if categoried %}
                    <form action="{% url 'index' %}" method="get">
                        {% csrf_token %}
                        <div class="form-group mx-sm-3 mb-2">
                            <select name="category" class="form-control" id="id_category">
                                <option value="">---Choose category---</option>
                                    {% for c in categoried %}
                                        <option value="{{c.id}}" {%if c.id == selected_category%} selected {%endif%}>{{c.name}}</option>
                                    {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-outline-primary mb-2">Search Category</button>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">title</th>
                        <th scope="col">description</th>
                        <th scope="col">website</th>
                        <th scope="col">category</th>
                        <th scope="col">publish</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in all_products %}
                        <tr class="text-center">
                            <td>{{ forloop.counter|add:offset }}</td>
                            <td>{{ product.title }}</td>
                            <td>{{ product.description|truncatechars:200 }}</td>
                            <td> <a href="{{ product.website }}" class="btn btn-primary">Visit Link</a></td>
                            <td>{{ product.category }}</td>
                            <td>{{ product.publish|date:"Y-m-d" }}</td>
                            <td>
                                <a class="btn btn-outline-primary mb-2" href='update_product/{{product.id}}?page={{page}}&selected_category={{selected_category}}'>Update Item</a>
                                <br/>
                                <a class="btn btn-outline-danger mb-2" href='javascript:DeleteProduct({{product.id}})'>Delete Item</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if not all_products %}
                        <tr>
                            <p>Enter your favorite RSS feed above.</p>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
            {% include "rss/pagination.html" with page=all_products %}
        </div>
    </div>

<script>
  function DeleteProduct(id) {
    if(confirm('Do you want to delete?')) {
        location.href = '/delete_product/' + id;
    }
  }
</script>
{% endblock %}